version: '3.2'

services:
  ddns:
    image: allandequeiroz/cloudflare-ddns
    restart: always
    environment:
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - CLOUDFLARE_API_EMAIL=${CLOUDFLARE_API_EMAIL}
      - CLOUDFLARE_API_DOMAIN=${CLOUDFLARE_API_DOMAIN}

